{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation-core/1.2.0-alpha01-dev774/animation-core-1.2.0-alpha01-dev774.module",
    "group": "org.jetbrains.compose.animation",
    "module": "animation-core",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.2.0-alpha01-dev774.jar",
          "url": "animation-core-desktop-1.2.0-alpha01-dev774.jar",
          "size": 313924,
          "sha512": "ade8f567ea19f9c5201c4a6ce246b389d507035de4ee05782c37a64f276b5bffec44a3db4c204d0781c046a2bee65978ac662e6a22a5062ff75f4f7da7c5ace6",
          "sha256": "f0c3a21f83eee5aaaef7566b9c9301f2ddcd34d1276c6d312a15a042879d0024",
          "sha1": "ee6b2acbcb6876a522de6601b403b0a97e5e1146",
          "md5": "7361a63d91c29ba3bdbca736d24d0a12"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-desktop-1.2.0-alpha01-dev774.jar",
          "url": "animation-core-desktop-1.2.0-alpha01-dev774.jar",
          "size": 313924,
          "sha512": "ade8f567ea19f9c5201c4a6ce246b389d507035de4ee05782c37a64f276b5bffec44a3db4c204d0781c046a2bee65978ac662e6a22a5062ff75f4f7da7c5ace6",
          "sha256": "f0c3a21f83eee5aaaef7566b9c9301f2ddcd34d1276c6d312a15a042879d0024",
          "sha1": "ee6b2acbcb6876a522de6601b403b0a97e5e1146",
          "md5": "7361a63d91c29ba3bdbca736d24d0a12"
        }
      ]
    }
  ]
}