{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.material",
    "module": "material-icons-core",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-metadata-1.2.0-alpha01-dev774.jar",
          "url": "material-icons-core-1.2.0-alpha01-dev774.jar",
          "size": 14038,
          "sha512": "5ed546a14434cfdc73371a62ac735227df30233736e6c36a4beb2f180195cd7d5116c07ea12513007577920bc345b5a26f86936cb1afa4451095dbaf2ba2f830",
          "sha256": "8ec377991b280ef792170d2db997ae47b39e2453ff83dbfef5c826dda4384ccf",
          "sha1": "3ad4403e6b5375cf3241ea09631ad817b03e31ef",
          "md5": "d9fdadfc67036b16bb5b174a7df9576b"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-icons-core-desktop/1.2.0-alpha01-dev774/material-icons-core-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material-icons-core-desktop/1.2.0-alpha01-dev774/material-icons-core-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material-icons-core-js/1.2.0-alpha01-dev774/material-icons-core-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../material-icons-core-js/1.2.0-alpha01-dev774/material-icons-core-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-macosarm64/1.2.0-alpha01-dev774/material-icons-core-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-macosarm64/1.2.0-alpha01-dev774/material-icons-core-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-macosx64/1.2.0-alpha01-dev774/material-icons-core-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-macosx64/1.2.0-alpha01-dev774/material-icons-core-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitarm64/1.2.0-alpha01-dev774/material-icons-core-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitarm64/1.2.0-alpha01-dev774/material-icons-core-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitsimarm64/1.2.0-alpha01-dev774/material-icons-core-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitsimarm64/1.2.0-alpha01-dev774/material-icons-core-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitx64/1.2.0-alpha01-dev774/material-icons-core-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../material-icons-core-uikitx64/1.2.0-alpha01-dev774/material-icons-core-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.material",
        "module": "material-icons-core-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}