{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-geometry",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-geometry-metadata-1.2.0-alpha01-dev774.jar",
          "url": "ui-geometry-1.2.0-alpha01-dev774.jar",
          "size": 6862,
          "sha512": "340e954dfde8980ddfc97edbbd57a6a98f5f39eef45cb0d22edb36526334ca26f948e017ed630cabb68027dc53a64da603ea14976d433b1a3065dbfff345ede1",
          "sha256": "aca76fdece9e4cffb71e54c7093c51c8b042425ef053720cfc83355ae3049ffd",
          "sha1": "151f5cb87874a70ab11f6b5a0103c432f670dd2c",
          "md5": "99025b5ac64a4796309c148273c198a8"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-geometry-desktop/1.2.0-alpha01-dev774/ui-geometry-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-geometry-desktop/1.2.0-alpha01-dev774/ui-geometry-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-geometry-js/1.2.0-alpha01-dev774/ui-geometry-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-geometry-js/1.2.0-alpha01-dev774/ui-geometry-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-macosarm64/1.2.0-alpha01-dev774/ui-geometry-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-macosarm64/1.2.0-alpha01-dev774/ui-geometry-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-macosx64/1.2.0-alpha01-dev774/ui-geometry-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-macosx64/1.2.0-alpha01-dev774/ui-geometry-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitarm64/1.2.0-alpha01-dev774/ui-geometry-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitarm64/1.2.0-alpha01-dev774/ui-geometry-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitsimarm64/1.2.0-alpha01-dev774/ui-geometry-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitsimarm64/1.2.0-alpha01-dev774/ui-geometry-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitx64/1.2.0-alpha01-dev774/ui-geometry-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-geometry-uikitx64/1.2.0-alpha01-dev774/ui-geometry-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-geometry-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}