{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-graphics",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-metadata-1.2.0-alpha01-dev774.jar",
          "url": "ui-graphics-1.2.0-alpha01-dev774.jar",
          "size": 42826,
          "sha512": "c34b936fa85dd352331b9d8beb60059df1a3d579b2e5ef717a0c77850fb747c1886aa97acdb5a10b55ec5119c559b43e4889532fc6382517bc313ed152708646",
          "sha256": "c714e46bc804880f964d764d8a896e1c0a498cd06fa2e0a64aff9c1f660300dd",
          "sha1": "e9c813a89f6d437df1d7a0c5757a6f3d8f334cfc",
          "md5": "3fd48d728910127de03f155b639ce62a"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.2.0-alpha01-dev774/ui-graphics-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-graphics-desktop/1.2.0-alpha01-dev774/ui-graphics-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-graphics-js/1.2.0-alpha01-dev774/ui-graphics-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-graphics-js/1.2.0-alpha01-dev774/ui-graphics-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-macosarm64/1.2.0-alpha01-dev774/ui-graphics-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-macosarm64/1.2.0-alpha01-dev774/ui-graphics-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-macosx64/1.2.0-alpha01-dev774/ui-graphics-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-macosx64/1.2.0-alpha01-dev774/ui-graphics-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitarm64/1.2.0-alpha01-dev774/ui-graphics-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitarm64/1.2.0-alpha01-dev774/ui-graphics-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitsimarm64/1.2.0-alpha01-dev774/ui-graphics-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitsimarm64/1.2.0-alpha01-dev774/ui-graphics-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitx64/1.2.0-alpha01-dev774/ui-graphics-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-graphics-uikitx64/1.2.0-alpha01-dev774/ui-graphics-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-graphics-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}