{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling-preview/1.2.0-alpha01-dev774/ui-tooling-preview-1.2.0-alpha01-dev774.module",
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-desktop-1.2.0-alpha01-dev774.jar",
          "url": "ui-tooling-preview-desktop-1.2.0-alpha01-dev774.jar",
          "size": 1863,
          "sha512": "8d0697191a4d20e79b9adc1d1d4016af39afd139366242b2da1b5c65b63dcab2cfa27b487db11f0de27bd3942be783517b64f2d811d353be9f53b81c61fcd894",
          "sha256": "db49ff56acf0a3c0f3062ed744c0cd3498dedf8a2785fe91cc6d6a64bfd4b99a",
          "sha1": "b57e16cd7cca67c9aa0bfb85aba98e393c486771",
          "md5": "597f98f6b3c92d7983057a1163f7e8d0"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-desktop-1.2.0-alpha01-dev774.jar",
          "url": "ui-tooling-preview-desktop-1.2.0-alpha01-dev774.jar",
          "size": 1863,
          "sha512": "8d0697191a4d20e79b9adc1d1d4016af39afd139366242b2da1b5c65b63dcab2cfa27b487db11f0de27bd3942be783517b64f2d811d353be9f53b81c61fcd894",
          "sha256": "db49ff56acf0a3c0f3062ed744c0cd3498dedf8a2785fe91cc6d6a64bfd4b99a",
          "sha1": "b57e16cd7cca67c9aa0bfb85aba98e393c486771",
          "md5": "597f98f6b3c92d7983057a1163f7e8d0"
        }
      ]
    }
  ]
}