{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-tooling-preview",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling-preview-metadata-1.2.0-alpha01-dev774.jar",
          "url": "ui-tooling-preview-1.2.0-alpha01-dev774.jar",
          "size": 720,
          "sha512": "3e634671e4ce96adc0410acea12f57902451ebda3b3a8715e495a23cbf49a9ee54df67dc8db2d72fd5893e6170c5812b779ac6eb7d084eae73b7aba10fd58c20",
          "sha256": "7e005cf9e82cf7cd3224f20fb318052e735a013de182b520487d075f6bde8dd5",
          "sha1": "3ae3611bae1d80ea7235db9b5aacbe747ce2bd3e",
          "md5": "dd67a48c38ee5cdcd98d5cf3a9be349d"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-desktop/1.2.0-alpha01-dev774/ui-tooling-preview-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-tooling-preview-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-tooling-preview-desktop/1.2.0-alpha01-dev774/ui-tooling-preview-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-tooling-preview-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}