{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-text",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.0-alpha01-dev774"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.7.30"
          }
        }
      ],
      "files": [
        {
          "name": "ui-text-metadata-1.2.0-alpha01-dev774.jar",
          "url": "ui-text-1.2.0-alpha01-dev774.jar",
          "size": 52122,
          "sha512": "dab8071ade104d2d0d227eaebd98510a9b20edebca344c39133b4fa736614bbef50357059cdf8868a8f8f163e45d9eb8d95f16f01c57609a0386929c9bcff8e5",
          "sha256": "afbdda7291c7a0799877225ef19409a8aa54913da8d1daa1e8041a8bb122ed93",
          "sha1": "21bf6189ddd5c0e1c46fe4c275361819679e3b1c",
          "md5": "2641f8bc1cb036271fc20696a0c775d1"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-text-desktop/1.2.0-alpha01-dev774/ui-text-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-text-desktop/1.2.0-alpha01-dev774/ui-text-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-text-js/1.2.0-alpha01-dev774/ui-text-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-text-js/1.2.0-alpha01-dev774/ui-text-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-macosarm64/1.2.0-alpha01-dev774/ui-text-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-macosarm64/1.2.0-alpha01-dev774/ui-text-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-macosx64/1.2.0-alpha01-dev774/ui-text-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-macosx64/1.2.0-alpha01-dev774/ui-text-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitarm64/1.2.0-alpha01-dev774/ui-text-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitarm64/1.2.0-alpha01-dev774/ui-text-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitsimarm64/1.2.0-alpha01-dev774/ui-text-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitsimarm64/1.2.0-alpha01-dev774/ui-text-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitx64/1.2.0-alpha01-dev774/ui-text-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-text-uikitx64/1.2.0-alpha01-dev774/ui-text-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-text-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}