{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose",
    "module": "compose-gradle-plugin",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "size": 3280764,
          "sha512": "b1d950875aab5917bfd11af810289912bc1a42cf1870d3792925e9e26e748402d551a42adac202a15034bddbb2ba4299fcbab0e73489d7628e3dcd802b2dd02d",
          "sha256": "3661fa8c598a05dd0e458600e8ad03ff0f50c2acdc08e0261d79d7edd42006b1",
          "sha1": "df7236fb3176fecd84f7841d05e4c56ce43290ab",
          "md5": "321c2d450a34c5b3fdac1913186bd6fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "size": 3280764,
          "sha512": "b1d950875aab5917bfd11af810289912bc1a42cf1870d3792925e9e26e748402d551a42adac202a15034bddbb2ba4299fcbab0e73489d7628e3dcd802b2dd02d",
          "sha256": "3661fa8c598a05dd0e458600e8ad03ff0f50c2acdc08e0261d79d7edd42006b1",
          "sha1": "df7236fb3176fecd84f7841d05e4c56ce43290ab",
          "md5": "321c2d450a34c5b3fdac1913186bd6fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-javadoc.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-javadoc.jar",
          "size": 261,
          "sha512": "19f77f9e6ad1332a703a0ab8a23f89efa772920b9704340561d4cfddfe4a41035bcdf698b4dfec0870ce26cad2c9a804ea739c6a068aae974fe39f89dd109082",
          "sha256": "be0924dd5c487a0d71473278396c80a3a7a7f653f616b8fc8eada8c58ada3d21",
          "sha1": "da5707aa1d5c210fa5cc51a2f162dfe0daa27cc1",
          "md5": "b43d3eae5cf1480d9169733e77a04a7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-sources.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-sources.jar",
          "size": 601371,
          "sha512": "9c8b2a2732f31d8cda3a8d33c9b56fe13cd7ce690208f84e65726a7d4a1395dd40ddc1425c8ffc54a9073d2a29078ed6ccadcfcc051f8e86659f2f8ebdb9d713",
          "sha256": "65f7302d91970263e813d4117fe3e5f35e29f26b9a174c7fd90cc5b4adb091a5",
          "sha1": "7ef1b99a6e83f939ac51ec084543b162b060d4d0",
          "md5": "63b45779c2c0e0a8dfa2885fe8b1c45b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-shadow.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-shadow.jar",
          "size": 3280194,
          "sha512": "edc2cea2e2de5ca37e5a20e5733bd5b813b49518d92ef44cafcb439582673b041d074d7c0f6e661afbb92d8918e65400128211bc7c097295a297bea3e6913acf",
          "sha256": "ca14e5bb5dad20d5618c48b1252716ee2fb12b8e3ee620a5472ed29a7ee9f91a",
          "sha1": "2672670f6865d6cc7b68b1298eb12b12bd6d45a1",
          "md5": "affd3f1995e1600cede2abf662e57552"
        }
      ]
    }
  ]
}
