{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose",
    "module": "compose-gradle-plugin",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "size": 4310485,
          "sha512": "878281d78b1dbd4afb9c3912af5282064ccbb73c1a482eff08e9b007182811b67e7dd5b0ebcc6a7c75eb0c54c358bc96331f12661d003ba40bd4cbe07c166ef2",
          "sha256": "361e363742cbde7a3736eda1ba0a1e7eb889805c00ea40248f04b72faa00c18e",
          "sha1": "031908e0faa37fe15167f183581762de430df678",
          "md5": "3835fcbfb6bcb0290eade5c641346a39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774.jar",
          "size": 4310485,
          "sha512": "878281d78b1dbd4afb9c3912af5282064ccbb73c1a482eff08e9b007182811b67e7dd5b0ebcc6a7c75eb0c54c358bc96331f12661d003ba40bd4cbe07c166ef2",
          "sha256": "361e363742cbde7a3736eda1ba0a1e7eb889805c00ea40248f04b72faa00c18e",
          "sha1": "031908e0faa37fe15167f183581762de430df678",
          "md5": "3835fcbfb6bcb0290eade5c641346a39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-javadoc.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-javadoc.jar",
          "size": 261,
          "sha512": "19f77f9e6ad1332a703a0ab8a23f89efa772920b9704340561d4cfddfe4a41035bcdf698b4dfec0870ce26cad2c9a804ea739c6a068aae974fe39f89dd109082",
          "sha256": "be0924dd5c487a0d71473278396c80a3a7a7f653f616b8fc8eada8c58ada3d21",
          "sha1": "da5707aa1d5c210fa5cc51a2f162dfe0daa27cc1",
          "md5": "b43d3eae5cf1480d9169733e77a04a7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-sources.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-sources.jar",
          "size": 601371,
          "sha512": "9c8b2a2732f31d8cda3a8d33c9b56fe13cd7ce690208f84e65726a7d4a1395dd40ddc1425c8ffc54a9073d2a29078ed6ccadcfcc051f8e86659f2f8ebdb9d713",
          "sha256": "65f7302d91970263e813d4117fe3e5f35e29f26b9a174c7fd90cc5b4adb091a5",
          "sha1": "7ef1b99a6e83f939ac51ec084543b162b060d4d0",
          "md5": "63b45779c2c0e0a8dfa2885fe8b1c45b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha01-dev774-shadow.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha01-dev774-shadow.jar",
          "size": 3252199,
          "sha512": "4a7cd4e79b6199a958ddef9255853492df126e10e332503808bfe69a19e36089b5d9c8f1a84c344b79d9a3d911e809cc56e236307ed21a81c4590f0285c8aad0",
          "sha256": "9ea4711bcf9a60dd393a72fb2af45c4730e1668823e59faab0e992820c445759",
          "sha1": "132ebbd430f6c55be9e06f065aaf279285383155",
          "md5": "657f4a34341f1325568a5a622a8c41db"
        }
      ]
    }
  ]
}
