{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.ui",
    "module": "ui-util",
    "version": "1.2.0-alpha01-dev774",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-metadata-1.2.0-alpha01-dev774.jar",
          "url": "ui-util-1.2.0-alpha01-dev774.jar",
          "size": 4461,
          "sha512": "97bd6e5150e0b0a10a657e68b731bf7286cdfafba178fa0cffd19ecc0bc8ac30b70bd6e5b992d61ba89b24653800c59d5d7a9a551ff7024192f7b9ff3710545c",
          "sha256": "c3d6d2ac7fecb5bb3f59673ec538b0d6637f816b5ea124cdc21ea9d7c5c73e34",
          "sha1": "577eb9f4db11c38e57382ac985ba80ca1dd5fe37",
          "md5": "52f806dc9e5bc92273bec5540a2991cc"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        }
      ]
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-desktop/1.2.0-alpha01-dev774/ui-util-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-util-desktop/1.2.0-alpha01-dev774/ui-util-desktop-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-desktop",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-util-js/1.2.0-alpha01-dev774/ui-util-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ui-util-js/1.2.0-alpha01-dev774/ui-util-js-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-js",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-macosarm64/1.2.0-alpha01-dev774/ui-util-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-macosarm64/1.2.0-alpha01-dev774/ui-util-macosarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-macosarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-macosx64/1.2.0-alpha01-dev774/ui-util-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-macosx64/1.2.0-alpha01-dev774/ui-util-macosx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-macosx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitarm64/1.2.0-alpha01-dev774/ui-util-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitarm64/1.2.0-alpha01-dev774/ui-util-uikitarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitsimarm64/1.2.0-alpha01-dev774/ui-util-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitSimArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitsimarm64/1.2.0-alpha01-dev774/ui-util-uikitsimarm64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitsimarm64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitx64/1.2.0-alpha01-dev774/ui-util-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    },
    {
      "name": "uikitX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ui-util-uikitx64/1.2.0-alpha01-dev774/ui-util-uikitx64-1.2.0-alpha01-dev774.module",
        "group": "org.jetbrains.compose.ui",
        "module": "ui-util-uikitx64",
        "version": "1.2.0-alpha01-dev774"
      }
    }
  ]
}