{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose.compiler",
    "module": "compiler",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compiler-1.3.0-alpha01.jar",
          "url": "compiler-1.3.0-alpha01.jar",
          "size": 961219,
          "sha512": "b21c81e5b2f438f0a990a623a1e601cc0759cff7f392dd90bd3369b2c4893f8a989f9bbb811705bfc21ad1d2e9646b8b6c3022ef9898fb6c9ec26308a8d5943b",
          "sha256": "65cd24391b91f6f12a41025ae08fa35862ef650872d8f1ceae6f410e59080806",
          "sha1": "d168d34a6568b2f6a9266e56e445a57f903bde97",
          "md5": "b740a05476ad0aeeb436dc16962024d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.0-alpha01.jar",
          "url": "compiler-1.3.0-alpha01.jar",
          "size": 961219,
          "sha512": "b21c81e5b2f438f0a990a623a1e601cc0759cff7f392dd90bd3369b2c4893f8a989f9bbb811705bfc21ad1d2e9646b8b6c3022ef9898fb6c9ec26308a8d5943b",
          "sha256": "65cd24391b91f6f12a41025ae08fa35862ef650872d8f1ceae6f410e59080806",
          "sha1": "d168d34a6568b2f6a9266e56e445a57f903bde97",
          "md5": "b740a05476ad0aeeb436dc16962024d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.0-alpha01-sources.jar",
          "url": "compiler-1.3.0-alpha01-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}